[build]
builder = "RAILPACK"
buildCommand = "pnpm turbo build --filter=web..."

watchPatterns = [
  "/apps/web/**",
  "/packages/ui-web/**",
  "/packages/contract/**",
  "/packages/api-client/**",
  "/packages/i18n/**",
  "/pnpm-lock.yaml",
  "/pnpm-workspace.yaml",
  "/turbo.json"
]

[deploy]
startCommand = "pnpm --filter=web start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
